---
title: 'Analyzing the affect of Redlining on LAs reported bird biodiversity'
author: "{Hazel Vaquero}"
output: html_document
date: "2023-12-15"
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(include = TRUE, message = FALSE, warning = FALSE)
```

# Background information

Current environmental injustice reflects legacies of the past. In the
1930's the Home Owners' Loan Corporation (HOLC), as part of the New
Deal, rated neighborhoods based on their perceived safety for real
estate investment. Their ranking system, (A (green), B (blue), C
(yellow), D (red)) was then used to block access to loans for home
ownership. This practice targeted and discriminated against minority
residents also known as redlining. This unjust practice is still felt to
this day as it halted economic development and impacted the health of
the residents[^1].

[^1]: Gee, G. C. (2008). A multilevel analysis of the relationship
    between institutional and individual racial discrimination and
    health status. American journal of public health, 98(Supplement_1),
    S48-S56.

A recent study found that redlining is also affecting the observations
of biodiversity[^2]. Ellis-Soto and co-authors found that redlined
neighborhoods remain the most under sampled areas across 195 US cities.
Observation like these rely on community or citizen scientist to
contribute and identify species. The gap in data is concerning because
conservation decisions are made based on these data.

[^2]: Ellis-Soto, D., Chapman, M., & Locke, D. H. (2023). Historical
    redlining is associated with increasing geographical disparities in
    bird biodiversity sampling in the United States. Nature Human
    Behaviour, 1-9.

This notebook will analyze L.A County reported bird diversity with
respect to redlining practices of the past. A recent study has found
that LA neighborhoods that are in a redlining district view less
diversity in birds[^3]. There are less canopy covers in lower income
neighborhoods and the birds found are those that are resilient to living
in urban settings. Reducing the biodiversity of birds that can survive
in these neighborhoods.

[^3]: Eric M Wood, Sevan Esaian, Christian Benitez, Philip J Ethington,
    Travis Longcore, Lars Y Pomara, Historical racial redlining and
    contemporary patterns of income inequality negatively affect birds,
    their habitat, and people in Los Angeles, California, Ornithological
    Applications, 2023;, duad044,
    <https://doi.org/10.1093/ornithapp/duad044>

# Data Used

1.  **EJScreen:** Environmental Protection Agency's Environmental
    Justice Screening and Mapping Tool.
    According to the [US EPA
    website](https://www.epa.gov/ejscreen/purposes-and-uses-ejscreen):

    > This screening tool and data may be of interest to community
    > residents or other stakeholders as they search for environmental
    > or demographic information. It can also support a wide range of
    > research and policy goals. The public has used EJScreen in many
    > different locations and in many different ways.

2.  **Mapping Inequality**

3.  **The [Global Biodiversity Information Facility](gbif.org)**

# Analysis

# Import Libraries
